#!/usr/bin/perl

my $in = $ARGV[0];
if (! defined $in){
    die "Usage: $0 filename";
}
my $out = $in;
$out =~ s/(\.\w+)/.out/;
if (! open $in_fh, "<", $in){
    die "Can't open '$in': $!";
}
if (! open $out_fh, ">", $out){
    die "Can't write '$out': $!";
}
while(<$in_fh>){
    chomp;
    s/Fred/\0/gi;
    s/Wilma/Fred/gi;
    s/\0/Wilma/g;
    print $out_fh $_;
}
