#!/usr/bin/perl
my %last_name = qw{ fred flinstone Wilma Flinstone Barney Rubble betty rubble Bamm-Bamm Rubble PEBBLES FLINSTONE };
my @keys = sort {"\L$last_name{$a}" cmp "\L$last_name{$b}" or "\L$a" cmp "\L$b"} keys %last_name;
foreach(@keys) {
    print "$last_name{$_}, $_\n";
}

