#!/usr/bin/perl

sub total {
    my $result;
    foreach (@_) {
        $result += $_; 
    }   
    $result;
}


sub above_average{
    my(@above);
    my $amount = @_;
    my $average = (total @_) / $amount;

    foreach (@_) {
        if ($_ > $average){
            push @above, $_;
        }
    }
    @above;
}

@fred = above_average(1..10);
print "\@fred is @fred\n";
print "(Should be 6 7 8 9 10)\n";

@barney = above_average(100, 1..10);
print "\@barney is @barney\n";
print "(Should be just 100)\n";
