#!/usr/bin/perl

use 5.010;

sub greet {
    state $last_person;
    my $name = shift;
    if ( defined($last_person)){
        print "Hi $name! $last_person is also here!\n";
        $last_person = $name;
    } else {
        print "Hi $name! You are the first one here!\n";
        $last_person = $name;
    }
}

greet("Fred");
greet("Barney");
